create table comentarios (
    id bigint generated by default as identity primary key,
    nombre text not null,
    comentario text not null,
    creado_en timestamptz default now()
);

alter table comentarios enable row level security;

create policy "Visitantes pueden enviar comentarios"
on comentarios
for insert
to anon
with check (
    length(nombre) between 1 and 100
    and length(comentario) between 1 and 2000
);

create policy "Administrador puede leer comentarios"
on comentarios
for select
to authenticated
using (true);

create policy "Administrador puede eliminar comentarios"
on comentarios
for delete
to authenticated
using (true);
